version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: inventory_db
    ports:
      - "27017:27017"
    networks:
      - server-network
  api:
    build:
      context: ./inventory-api
      dockerfile: Dockerfile
    container_name: inventory-api
    environment:
      - DB_URL=mongodb://mongodb:27017/inventory_db
    ports:
      - "8080:8080"
    networks:
      - server-network
    depends_on:
      - mongodb
    links:
      - mongodb
networks:
  server-network:
    driver: bridge
