/**
 * Elton's Inventory
 * Reboot
 *
 * OpenAPI spec version: 1.0.11
 * Contact: nhlana.2@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ToastrResponse { 
    message: string;
    /**
     * message type
     */
    type: ToastrResponse.TypeEnum;
}
export namespace ToastrResponse {
    export type TypeEnum = 'success' | 'warning' | 'error';
    export const TypeEnum = {
        Success: 'success' as TypeEnum,
        Warning: 'warning' as TypeEnum,
        Error: 'error' as TypeEnum
    };
}