/**
 * Elton's Inventory
 * Reboot
 *
 * OpenAPI spec version: 1.0.11
 * Contact: nhlana.2@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { InsertStockQuantityRequest } from '../model/insertStockQuantityRequest';
import { StockQuantity } from '../model/stockQuantity';
import { StockResponse } from '../model/stockResponse';
import { ToastrResponse } from '../model/toastrResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class StockQuantityService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Add stock item quantity
     * This endpoint add an adjustments to be made over a inventory item quantity
     * @param body stock item quantity
     * @param stockItemId stock item id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public stockQuantitiesControllerAddStockQuantity(body: InsertStockQuantityRequest, stockItemId: string, observe?: 'body', reportProgress?: boolean): Observable<StockResponse>;
    public stockQuantitiesControllerAddStockQuantity(body: InsertStockQuantityRequest, stockItemId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<StockResponse>>;
    public stockQuantitiesControllerAddStockQuantity(body: InsertStockQuantityRequest, stockItemId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<StockResponse>>;
    public stockQuantitiesControllerAddStockQuantity(body: InsertStockQuantityRequest, stockItemId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling stockQuantitiesControllerAddStockQuantity.');
        }

        if (stockItemId === null || stockItemId === undefined) {
            throw new Error('Required parameter stockItemId was null or undefined when calling stockQuantitiesControllerAddStockQuantity.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<StockResponse>('put',`${this.basePath}/stock-quantity/${encodeURIComponent(String(stockItemId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get stock captured quantity
     * This endpoint add returns captured stock quantities of an item
     * @param stockItemId stock item id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public stockQuantitiesControllerGetStockQuantity(stockItemId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<StockResponse>>;
    public stockQuantitiesControllerGetStockQuantity(stockItemId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<StockResponse>>>;
    public stockQuantitiesControllerGetStockQuantity(stockItemId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<StockResponse>>>;
    public stockQuantitiesControllerGetStockQuantity(stockItemId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (stockItemId === null || stockItemId === undefined) {
            throw new Error('Required parameter stockItemId was null or undefined when calling stockQuantitiesControllerGetStockQuantity.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<StockResponse>>('get',`${this.basePath}/stock-quantity/${encodeURIComponent(String(stockItemId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Remove stock item quantity
     * 
     * @param id id of item to remove
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public stockQuantitiesControllerRemoveStockItem(id: string, observe?: 'body', reportProgress?: boolean): Observable<ToastrResponse>;
    public stockQuantitiesControllerRemoveStockItem(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ToastrResponse>>;
    public stockQuantitiesControllerRemoveStockItem(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ToastrResponse>>;
    public stockQuantitiesControllerRemoveStockItem(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling stockQuantitiesControllerRemoveStockItem.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ToastrResponse>('delete',`${this.basePath}/stock-quantity/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update stock item
     * 
     * @param body stock item
     * @param id quantity id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public stockQuantitiesControllerUpdateStockItemQuantity(body: InsertStockQuantityRequest, id: string, observe?: 'body', reportProgress?: boolean): Observable<Array<StockQuantity>>;
    public stockQuantitiesControllerUpdateStockItemQuantity(body: InsertStockQuantityRequest, id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<StockQuantity>>>;
    public stockQuantitiesControllerUpdateStockItemQuantity(body: InsertStockQuantityRequest, id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<StockQuantity>>>;
    public stockQuantitiesControllerUpdateStockItemQuantity(body: InsertStockQuantityRequest, id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling stockQuantitiesControllerUpdateStockItemQuantity.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling stockQuantitiesControllerUpdateStockItemQuantity.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<StockQuantity>>('post',`${this.basePath}/stock-quantity/${encodeURIComponent(String(id))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
