/**
 * Gotbot
 * Gotbot app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: nhlana.2@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiProperty } from "@nestjs/swagger";

export class InsertStockQuantityRequest {
    @ApiProperty({
        example: '10',
        type: Number,
    })
    quantity: number;

    @ApiProperty({
        example: '10/01/2023',
        type: Date,
    })
    date: Date;
}

