/**
 * Gotbot
 * Gotbot app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: nhlana.2@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiProperty } from '@nestjs/swagger';

export class LoginResponse {
    @ApiProperty({
        type: 'string',
        example: 'pride',
    })
    name: string;
    @ApiProperty({
        type: 'string',
        example: '1ccfd5d1-dbe6-4871-9953-d9a7845cd9ea1ccfd5d1-dbe6-4871-9953-d9a7845cd9ea',
    })
    jwt: string;
}