/**
 * Gotbot
 * Gotbot app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: nhlana.2@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiProperty } from "@nestjs/swagger";

export class StockQuantity {

    @ApiProperty({
        example: 'fd3df093-9909-4f0c-b966-e62eecb58cdc',
        type: String,
    })
    _id: string;

    @ApiProperty({
        example: 'fd3df093-9909-4f0c-b966-e62eecb58cdc',
        type: String,
    })
    stockId: string;

    @ApiProperty({
        example: 10,
        type: Number,
    })
    quantity?: number;

    @ApiProperty({
        example: '01/01/01',
        type: Date,
    })
    date?: Date;
}

